config/routes.rb
Rails.application.routes.draw do
  
  #Estableciendo como pagina de inicio
  root 'welcome#index'
  
  #Metodos para el login
  
  get '/login', to: 'login#login'
  
  post '/login', to: 'login#create'

  #metodos para el menu
  get '/help', to: 'welcome#help'

  get '/about', to: 'welcome#about'
  
  #metodos para cerrar sesion
  delete '/logout', to: 'login#delete'

  #Metodos de favio
  get 'boton/btn'

  get 'formularios/por_get'

  get 'formularios/por_post'

  post "boton/btn" => "boton#btn"
  
  post "boton/imprimir" => "boton#imprimir"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boton_controller.rb
class BotonController < ApplicationController

  require "firebase_token_generator"

  def btn
    p "hola prros"
  end
  def imprimir
    p "hola kshorroz"
    firebase_url    = 'https://ayd2proyecto.firebaseio.com/'
    firebase_secret = 'l597FxVKrQwVpRVZ5rrCNYx4ArX8lNjGWCKqrGLk'


    firebase = Firebase::Client.new(firebase_url, firebase_secret)

    ##response = firebase.push("users", { :nombre => 'el prro de julian', :descripcion => 'es gigante y malvado',        :priority => 1 })
  
    response2 = firebase.get("users")
    parsed = JSON.parse(response2.raw_body)

    parsed.each do |p|
      cadena = p[1]['nombre']
      cadena2 = p[1]['descripcion']
      puts cadena
      puts cadena2
      puts ' '

      payload = {:uid => "1", :auth_data => "foo", :other_auth_data => "bar"}
      
      generator = Firebase::FirebaseTokenGenerator.new(firebase_secret)
      token = generator.create_token(payload)
      
      puts token
    end

  end
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
  def por_get
  end

  def por_post
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

 #Nuevo sesion
 def login

 end

 #Crear Sesion
 def create
   user = 

   if user && user.authenticate(params[:session][:password])
     #log user
   else  
     #el usuario no exite
     flash[:danger] = 'El Usuario o Contraseña son incorrectos'
     render new
   end
end

#finalizar Sesion
def destoy
end

#Metodo hecho por Favio
def compareExcel
  p "hola"
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
def new
end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boton_helper.rb
module BotonHelper
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boton/btn.html.erb
<h1>Boton#btn</h1>
<p>Find me in app/views/boton/btn.html.erb</p>

app/views/formularios/por_get.html.erb
<h1>Formularios#por_get</h1>
<p>Find me in app/views/formularios/por_get.html.erb</p>

app/views/formularios/por_post.html.erb
<h1>Formularios#por_post</h1>
<p>Find me in app/views/formularios/por_post.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AyD2 Proyecto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Dummys Transaction", '#', id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",  :controller => "welcome"  %></li>
          <li><%= link_to "Log in", :action => "login", :controller => "login"%></li>
          <li><%= link_to "About", '#' %></li>
        </ul>
      </nav>
    </div>
  </header>
  
    <div class="container">

    <%= yield %>

  </body>
</html>

app/views/login/login.html.erb
<h1> LOGIN </h1>

<div class ="row">
    <div class = "col-md-6 col-md-offset-3">
        <%= form_for(:welcome, url: login_path ) do |f|%>

            <%= f.label :email %>
            <%= f.email_field :email %>
            
            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.submit "Log in", class: "btn btn-primary" %>

        <% end %>
    </div>
</div>

<%= button_to "imprime prro", { :controller => "boton", :action => "btn"} %>
<%= button_to "imprime kshorro", { :controller => "boton", :action => "imprimir"} %>

app/views/welcome/index.html.erb
<div class="center jumbotron">
<h1>Bienvenidos</h1>

<h2>
  Bienvenidos, por medio de esta aplicación puede realizar 
  sus transacciones de manera segura y rápida. 
</h2>

<%= link_to "Iniciar Sesion",  :action => "login", :controller => "login", :html => { :class => "btn btn-lg btn-primary" } %>
</div>